<a href="https://colab.research.google.com/github/VarunKoduru/langchain/blob/main/Langchain_Prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
!{sys.executable} -m pip install -q --upgrade langchain-core langchain-community requests==2.32.4

In [ ]:
# Document Loaders in Langchain
from langchain_community.document_loaders import TextLoader

loader = TextLoader('/content/langchain.txt',encoding='utf-8')

docs = loader.load()

print(type(docs))
print(docs[0])
print(docs[0].page_content)
print(docs[0].metadata)

<class 'list'>
page_content='LangChain is an open-source framework designed to simplify the development of applications powered by large language models (LLMs). It provides developers with a structured way to build intelligent applications that can understand, generate, and process natural language. Rather than interacting with a language model directly, LangChain offers reusable components that help manage prompts, memory, external data sources, and workflows, making it easier to create scalable AI solutions.

One of the key features of LangChain is its ability to connect language models with external tools and data. It allows applications to retrieve information from databases, documents, APIs, and websites, enabling language models to generate responses based on up-to-date and domain-specific information. This approach, often called Retrieval-Augmented Generation (RAG), improves the accuracy and relevance of AI-generated responses while reducing the chances of producing incorrect or

In [ ]:
!pip install -qU \
langchain \
langchain-community \
langchain-core \
langchain-google-genai \
langsmith

In [ ]:
pip install -r "/content/requirements.txt"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.4/120.4 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.9/956.9 kB 32.7 MB/s eta 0:00:00


In [ ]:
import langchain

print(langchain.__version__)

1.3.11


In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Example: query embedding
query = np.array([[0.1, 0.2, 0.3]])

# Example: vector store (3 document embeddings)
vector_store = np.array([
    [0.1, 0.2, 0.25],
    [0.9, 0.1, 0.3],
    [0.05, 0.2, 0.35]
])

# Compute cosine similarity
similarities = cosine_similarity(query, vector_store)

print("Cosine similarities:", similarities[0])
# Output: [0.998..., 0.707..., 0.995...]
print(query)
print(vector_store)



[0.1 0.2 0.3]
[[0.1  0.2  0.25]
 [0.9  0.1  0.3 ]
 [0.05 0.2  0.35]]


In [ ]:
def l_d(fn):
  with open(fn,'r',encoding="utf-8") as f:
    return f.read()

text = l_d("/content/sx.txt").replace(".","")
text1 = text.split()


def ch(t,overlap,chunk_size):
  chunks = []
  step = chunk_size - overlap
  for i in range(0,len(t),step):
    temp = " ".join(t[i:i+chunk_size])
    if temp:
      chunks.append(temp)
    if i + chunk_size >= len(t):
      break
  return chunks

res = ch(text1,20,40)
for r in res:
  print(r)



Artificial Intelligence is a field of computer science that focuses on creating systems that can perform tasks that normally require human intelligence Machine Learning is a subset of Artificial Intelligence It allows computers to learn patterns from data without being
human intelligence Machine Learning is a subset of Artificial Intelligence It allows computers to learn patterns from data without being explicitly programmed for every task Supervised Learning is a type of machine learning where the model learns from labeled training
explicitly programmed for every task Supervised Learning is a type of machine learning where the model learns from labeled training data Classification and regression are common examples of supervised learning Unsupervised Learning works with unlabeled data Clustering is one of
data Classification and regression are common examples of supervised learning Unsupervised Learning works with unlabeled data Clustering is one of the most common unsupervised learni

In [3]:
pip install fastembed


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.6/116.6 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 59.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.1/324.1 kB 19.0 MB/s eta 0:00:00


In [ ]:
import numpy as np
from fastembed import TextEmbedding

e = TextEmbedding()
vec = np.array(list(e.embed(res)))
print(vec)
print(len(vec))

[[-0.00127107 -0.02130936  0.00220419 ...  0.04613476  0.04339118
  -0.06829648]
 [-0.00746619 -0.02326674 -0.0117469  ...  0.03074629  0.03125383
  -0.07100229]
 [ 0.00985413 -0.04672379 -0.03685632 ... -0.00643386  0.03410944
  -0.00103425]
 ...
 [-0.05154419 -0.01294573  0.00882724 ... -0.0330806   0.02005528
  -0.02112967]
 [-0.04385841 -0.03604909 -0.00026725 ...  0.00435166  0.03928325
  -0.0234937 ]
 [-0.03731763 -0.027532    0.00086203 ...  0.02323426  0.06754728
  -0.00926329]]
11


In [ ]:
import numpy as np
from fastembed import TextEmbedding


def fn(file):
  with open(file,"r",encoding="utf-8") as f:
    text = f.read().replace(".","")
    t1 = text.split()
    return t1

def ch(chunks,ol,cs):
  cx = []
  step = cs -  ol
  for i in range(0,len(chunks),step):
    temp = " ".join(chunks[i:i+cs])
    if temp:
      cx.append(temp)
    if i+cs >= len(chunks):
      break

  return cx

def em(cks):
  em = TextEmbedding()
  vs = np.array(list(em.embed(cks)))
  return vs

def cosine(q_e, v_e):

    q_n = np.linalg.norm(q_e)
    v_n = np.linalg.norm(v_e, axis=1)

    sc = np.dot(v_e, q_e) / (v_n * q_n)

    return sc

def sm(vs,q,k,cx):
  e_model = TextEmbedding()
  qs = np.array(list(e_model.embed([q])))[0]

  scores = cosine(qs,vs)

  top_ind = np.argsort(scores)[::-1][:k]
  res = []
  for i in top_ind:
    res.append({
        "chunk":cx[i],
        "score":float(scores[i])
    })


  return res

def main():
  tokens = fn("/content/sx.txt")
  chunks = ch(tokens,20,80)
  vs = em(chunks)
  q = "What is supervised learning ?"
  result = sm(vs,q,3,chunks)
  for x in result:
    print(x)

main()


{'chunk': 'Artificial Intelligence is a field of computer science that focuses on creating systems that can perform tasks that normally require human intelligence Machine Learning is a subset of Artificial Intelligence It allows computers to learn patterns from data without being explicitly programmed for every task Supervised Learning is a type of machine learning where the model learns from labeled training data Classification and regression are common examples of supervised learning Unsupervised Learning works with unlabeled data Clustering is one of', 'score': 0.7556194067001343}
{'chunk': 'data Classification and regression are common examples of supervised learning Unsupervised Learning works with unlabeled data Clustering is one of the most common unsupervised learning techniques Deep Learning is a subset of machine learning that uses artificial neural networks with multiple layers Deep learning is widely used in computer vision, natural language processing and speech recognitio

In [4]:
from fastembed import ImageEmbedding

model = ImageEmbedding("Qdrant/clip-ViT-B-32-vision")

image_path = "/content/jenna-ortega.jpg"

embedding = list(model.embed([image_path]))[0]

print("Embedding dimensions:", len(embedding))
print(embedding[:10])

Reconstructing (incomplete total...): |          |  0.00B /  0.00B            

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Embedding dimensions: 512
[-0.02105399  0.0320205  -0.01761396  0.02874852 -0.01513132  0.07958221
  0.0232184  -0.02170737 -0.02005639 -0.00496488]
